## 가상환경

터미널
py --list
py -3.13 --version
py -3.13 -m venv .venv

가상환경
.ven\Scripts\activate 복사

deactivate

pip list
pip install ipykernel

powershall X
command prompt 누르고 다시 실행

python -m pip ~~

In [1]:
# 가상환경
print('Hello')

Hello


## 클래스

In [13]:
class Student:
    population = 0 # 클래스 변수 (공유)

    def __init__(self, name, age): # 생성자
        self.name = name # 인스턴스 변수
        self.age = age
        Student.population += 1

    # 매서드
    def hello(self):
        print(f'{self.name}님 안녕하세요.')


In [ ]:
# 상속
class NewStudent(Student):
    population = 0 # 클래스 변수 (공유)

    # 새로운 메서드
    def study(self):
        print(f'{self.name}님 공부하세요.')

    # 메서드 오버라이딩 (메서드 재정의)
    def hello(self):
        print(f'{self.name}님 신~나게 안녕하세요.')

In [27]:
std3 = NewStudent('정윤교', 25)

In [28]:
std3.hello()

정윤교님 신~나게 안녕하세요.


In [9]:
std1 = Student('임원묵', 26)

In [10]:
std1.population

1

In [11]:
std2 = Student('최동건', 25)

In [12]:
std1.population

2

In [7]:
std2.hello() # name님 안녕하세요

최동건님 안녕하세요.


## 넘파이

In [31]:
import numpy

In [ ]:
%pip install numpy
# python -m pip install numpy (터미널용)

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------------------- ------------------- 6.3/12.6 MB 49.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 43.1 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [32]:
import numpy as np

In [33]:
np.__version__

'2.5.3'

In [34]:
alist = [1,2,3,4,5]

In [36]:
print(type(alist))

<class 'list'>


In [41]:
print(alist)

[1, 2, 3, 4, 5]


In [42]:
print(ar)

[1 2 3 4 5]


In [39]:
ar = np.array(alist)

In [43]:
print(type(ar))

<class 'numpy.ndarray'>


In [48]:
blist = [1,'2',2.2,4]

In [53]:
ar1 = np.array(blist, dtype='int')

In [54]:
ar1.ndim

1

In [55]:
ar1.shape

(4,)

In [ ]:
[[1,2,3,4], [5,6,7,8], [9,10,11,12]]

In [57]:
ar2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
ar2.shape

(3, 4)

In [60]:
ar3 = ar2.reshape(2, 2, 3)
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
ar3.shape

(2, 2, 3)

In [63]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,10])

In [68]:
[1,2,3,4,5] + [2,3,4,5,6]

[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]

In [67]:
alist - 1

array([0, 1, 2, 3, 4])

In [70]:
alist * blist

array([ 6, 14, 24, 36, 50])

In [77]:
(alist == 2) | (blist > 9)

array([False,  True, False, False,  True])

In [78]:
import time

time.time()

1789614804.098651

In [79]:
size = 1000000
py_list = list(range(size))
np_array = np.arange(size)

In [80]:
start_time = time.time()
[i * 2 for i in py_list]
end_time = time.time()
print(end_time - start_time)

start_time = time.time()
np_array * 2
end_time = time.time()
print(end_time - start_time)

0.07138776779174805
0.003467559814453125


In [81]:
alist = [[0,1,2], [3,4,5]]

In [82]:
alist

[[0, 1, 2], [3, 4, 5]]

In [83]:
alist[-1][-1]

5

In [86]:
alist[0][:2]

[0, 1]

In [87]:
alist = [[0, 1, 2],
         [3, 4, 5]]

In [88]:
[alist[0][1], alist[1][1]]

[1, 4]

In [89]:
blist = np.array(alist)
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
print(blist[-1][-1])

5


In [92]:
blist[0][:2]

array([0, 1])

In [93]:
[blist[0][1], blist[1][1]]

[np.int64(1), np.int64(4)]

In [94]:
blist[-1,-1]

np.int64(5)

In [95]:
blist[0,:2]

array([0, 1])

In [99]:
blist[0,1],[1,1]

(np.int64(1), [1, 1])